USE VENTAS_JUGOS;

CREATE TABLE tb_vendedor(
MATRICULA VARCHAR(5) NOT NULL,
NOMBRE VARCHAR(100) DEFAULT NULL,
BARRIO VARCHAR(50) DEFAULT NULL,
COMISION FLOAT DEFAULT NULL,
FECHA_ADMISION DATE DEFAULT NULL,
DE_VACACIONES BIT(1) DEFAULT NULL,
PRIMARY KEY (MATRICULA)
);

CREATE TABLE tb_producto(
CODIGO VARCHAR(10) NOT NULL,
DESCRIPCION VARCHAR(100) DEFAULT NULL,
SABOR VARCHAR(50) DEFAULT NULL,
TAMANO VARCHAR(50) DEFAULT NULL,
ENVASE VARCHAR(50) DEFAULT NULL,
PRECIO_LISTA FLOAT DEFAULT NULL,
PRIMARY KEY (CODIGO)
);

CREATE TABLE tb_cliente(
DNI VARCHAR(10) NOT NULL,
NOMBRE VARCHAR(50) DEFAULT NULL,
DIRECCION VARCHAR(50) DEFAULT NULL,
BARRIO VARCHAR(50) DEFAULT NULL,
CIUDAD VARCHAR(50) DEFAULT NULL,
ESTADO VARCHAR(50) DEFAULT NULL,
CP VARCHAR(10) DEFAULT NULL,
FECHA_NACIMIENTO DATE DEFAULT NULL,
EDAD SMALLINT(2) DEFAULT NULL,
SEXO VARCHAR(1) DEFAULT NULL,
LIMITE_CREDITO FLOAT DEFAULT NULL,
VOLUMEN_COMPRA FLOAT DEFAULT NULL,
PRIMERA_COMPRA BIT(1) DEFAULT NULL,
PRIMARY KEY(DNI)
);

/*ALTER TABLE tb_cliente
MODIFY DNI VARCHAR(10) NOT NULL;*/

CREATE TABLE factura(
NUMERO INT(10) NOT NULL,
FECHA DATE DEFAULT NULL,
DNI VARCHAR(8) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPUESTO FLOAT DEFAULT NULL,
PRIMARY KEY(NUMERO)
);