
/* VENTAS REALIZADAS POR SABOR EN EL 2016, LA CANTIDAD DE LITROS
Y PORCENTAJE DE PARTICIPACIÓN DE ESTAS VENTAS EN ORDEN DESCENDENTE */

SELECT P.SABOR, I.CANTIDAD, F.FECHA_VENTA FROM
tabla_de_productos P
INNER JOIN
items_facturas I
ON P.CODIGO_DEL_PRODUCTO = I.CODIGO_DEL_PRODUCTO
INNER JOIN
FACTURAS F
ON F.NUMERO = I.NUMERO;

/* CANTIDAD VENDIDA POR SABOR AÑO 2016 */

SELECT P.SABOR, SUM(I.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM
tabla_de_productos P
INNER JOIN
items_facturas I
ON P.CODIGO_DEL_PRODUCTO = I.CODIGO_DEL_PRODUCTO
INNER JOIN
FACTURAS F
ON F.NUMERO = I.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY P.SABOR, YEAR(F.FECHA_VENTA)
ORDER BY SUM(I.CANTIDAD) DESC;


/* CANTIDAD TOTAL DE VENTAS */

SELECT SUM(I.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM
tabla_de_productos P
INNER JOIN
items_facturas I
ON P.CODIGO_DEL_PRODUCTO = I.CODIGO_DEL_PRODUCTO
INNER JOIN
FACTURAS F
ON F.NUMERO = I.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY YEAR(F.FECHA_VENTA);


SELECT * FROM (

SELECT P.SABOR, SUM(I.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM
tabla_de_productos P
INNER JOIN
items_facturas I
ON P.CODIGO_DEL_PRODUCTO = I.CODIGO_DEL_PRODUCTO
INNER JOIN
FACTURAS F
ON F.NUMERO = I.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY P.SABOR, YEAR(F.FECHA_VENTA)
ORDER BY SUM(I.CANTIDAD) DESC) VENTA_SABOR
INNER JOIN (SELECT SUM(I.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM
tabla_de_productos P
INNER JOIN
items_facturas I
ON P.CODIGO_DEL_PRODUCTO = I.CODIGO_DEL_PRODUCTO
INNER JOIN
FACTURAS F
ON F.NUMERO = I.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY YEAR(F.FECHA_VENTA)) VENTA_TOTAL
ON VENTA_TOTAL.AÑO = VENTA_SABOR.AÑO;

/* Modifica el informe pero ahora para ver el ranking de las ventas por tamaño. */

SELECT VENTAS_TAMANO.TAMANO, VENTAS_TAMANO.AÑO, VENTAS_TAMANO.CANTIDAD_TOTAL,
ROUND((VENTAS_TAMANO.CANTIDAD_TOTAL / VENTA_TOTAL.CANTIDAD_TOTAL) * 100, 2) AS PORCENTAJE FROM (

SELECT P.TAMANO, SUM(I.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM
tabla_de_productos P
INNER JOIN
items_facturas I
ON P.CODIGO_DEL_PRODUCTO = I.CODIGO_DEL_PRODUCTO
INNER JOIN
FACTURAS F
ON F.NUMERO = I.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY P.TAMANO, YEAR(F.FECHA_VENTA)
ORDER BY SUM(I.CANTIDAD) DESC) VENTAS_TAMANO
INNER JOIN (SELECT SUM(I.CANTIDAD) AS CANTIDAD_TOTAL, YEAR(F.FECHA_VENTA) AS AÑO FROM
tabla_de_productos P
INNER JOIN
items_facturas I
ON P.CODIGO_DEL_PRODUCTO = I.CODIGO_DEL_PRODUCTO
INNER JOIN
FACTURAS F
ON F.NUMERO = I.NUMERO
WHERE YEAR(F.FECHA_VENTA) = 2016
GROUP BY YEAR(F.FECHA_VENTA)) VENTA_TOTAL
ON VENTA_TOTAL.AÑO = VENTAS_TAMANO.AÑO
ORDER BY VENTAS_TAMANO.CANTIDAD_TOTAL DESC;

