/* Comandos realizados en CMD */

-- COST 8849.05
-- EXPLAIN FORMAT = JSON SELECT * FROM FACTURAS WHERE FECHA_VENTA = '20170101' \G;

-- COST 25.90
ALTER TABLE FACTURAS ADD INDEX(FECHA_VENTA);
-- EXPLAIN FORMAT = JSON SELECT * FROM FACTURAS WHERE FECHA_VENTA = '20170101' \G;

-- COST 8849.05
 ALTER TABLE FACTURAS DROP INDEX FECHA_VENTA;
 -- EXPLAIN FORMAT = JSON SELECT * FROM FACTURAS WHERE FECHA_VENTA = '20170101' \G;